### PR TITLE
Updating the Parser to properly parse the example contract

### PR DESCRIPTION
**Pull request by mariari**

### CODE REVIEW

**Comment by cwgoes** [comment]
Looking good - can we actually just set up the tests to load example contracts from files (instead of inlining them as strings)? I'm sure we'll want to do that eventually to keep the tests manageable.

**Comment by mariari** [comment]
> Looking good - can we actually just set up the tests to load example contracts from files (instead of inlining them as strings)? I'm sure we'll want to do that eventually to keep the tests manageable.

Yes, though I wasn't sure where the file would live, so I made a macro to copy line by line.

It's easy enough to read.

**Comment by cwgoes** [comment]
We can just make a `test/contracts` directory or the like.

**Comment by cwgoes** [comment]
- [ ] Also treat terms & types in the same syntactic fashion

**Pull request merged**
