### PR TITLE
WIP: Adding Agda code documentation generation

### PR DESCRIPTION
**Pull request by mariari**

### CODE REVIEW

**Comment by cwgoes** [comment]
Should this be moved to the new org-generation repository? @mariari

**Comment by mariari** [comment]
> Should this be moved to the new org-generation repository? @mariari

Yes, however I'm not sure how to copy over PR's so I'll leave this open until I copy it there!

**Comment by cwgoes** [comment]
Bump @mariari

**Comment by mariari** [comment]
Okay, opened a new issue [here](https://github.com/cryptiumlabs/Org-Generation/pull/7).

@andy-morris feel free to try it out!

Closing this issue

**Pull request closed without merging**
